# This is an example credential file
# 
# The raw credentials are separated from the config file in the case that 
# a change is needed in the database config file

database: madison_database
username: username
password: password

admin_email: admin@example.com
admin_fname: Venustiano
admin_lname: Carranza
admin_password: password

user_email: user@example.com
user_fname: John
user_lname: Appleseed
user_password: password
